import { montarMarco } from '../componentes/marco.js';
import { api, subirImagen } from '../componentes/api.js';
import { leerJSON } from '/src/servicios/archivos.js';
import { validarProyectos } from '/src/servicios/validadores/proyectos.js';
montarMarco();
const el=id=>document.getElementById(id);
const n=(tag,text)=>{const e=document.createElement(tag);if(text!==undefined)e.textContent=text;return e;};
let c,revision,t,a,dirty=false,editando=false,abierto=false,busy=false;
const uid=prefix=>prefix+'-'+crypto.randomUUID().slice(0,8);
const aviso=s=>el('estado').textContent=s;
const boton=(s,fn)=>{const b=n('button',s);b.type='button';b.onclick=fn;return b;};
function modificado(){dirty=true;aviso(a.pendiente);}
function controls(){el('guardar').disabled=busy||editando;el('respaldos').disabled=busy||editando;}
function lista(){abierto=false;editando=false;controls();el('editor').replaceChildren();const bar=n('div');bar.className='admin-acciones';bar.append(boton(a.nuevo,()=>editar(nuevo(),true)),boton(a.configuracion,configurar));el('editor').append(bar);const search=n('input');search.type='search';search.placeholder=a.buscar;search.setAttribute('aria-label',a.buscar);el('editor').append(search);const list=n('div');list.className='admin-proyecto-lista';el('editor').append(list);
 function render(){list.replaceChildren();const text=search.value.toLowerCase();for(const p of [...c.proyectos].sort((x,y)=>x.orden-y.orden).filter(p=>p.nombre.toLowerCase().includes(text))){const row=n('article');row.className='admin-proyecto-row';const img=n('img');img.src=p.imagen;img.alt='';const info=n('div');info.append(n('h2',p.nombre),n('p',(c.categorias.find(x=>x.id===p.categoria)?.nombre||'')+' · '+t.estados[p.estado]+' · '+(p.visible?a.visibleTexto:a.ocultoTexto)));const act=n('div');act.className='admin-proyecto-acciones';act.append(boton(a.editar,()=>editar(p)),boton(a.duplicar,()=>{const copy=structuredClone(p);copy.id=uid('proyecto');copy.ruta='/paginas/proyectos/detalle/index.html?id='+copy.id;copy.nombre+=' ('+a.duplicado+')';copy.visible=false;copy.orden=c.proyectos.length;editar(copy,true);}),boton(p.visible?a.ocultar:a.mostrar,()=>{p.visible=!p.visible;modificado();render();}),boton(a.eliminar,()=>{if(confirm(a.confirmarEliminar)){c.proyectos=c.proyectos.filter(x=>x.id!==p.id);modificado();render();}}));const ver=n('a',a.ver);ver.href=p.ruta;ver.target='_blank';ver.rel='noopener';act.append(ver);info.append(act);row.append(img,info);list.append(row);}}search.oninput=render;render();}
function nuevo(){const id=uid('proyecto');return {id,nombre:a.nuevoNombre,categoria:c.categorias[0].id,resumen:a.nuevoResumen,estado:'concepto',visible:false,destacado:false,orden:c.proyectos.length,formato:'normal',imagen:'/assets/imagenes/proyectos/proceso-diseno.webp',alternativo:a.nuevoNombre,alcance:a.nuevoAlcance,enfoque:a.nuevoEnfoque,nota:c.presentacion.nota,ruta:'/paginas/proyectos/detalle/index.html?id='+id,producto:'',mostrarEtapas:true,mostrarDetalles:true,mostrarGaleria:true,materiales:a.nuevosMateriales,detalles:[],etapas:[],galeria:[],videos:[],mensaje:a.nuevoMensaje};}
function formBase(title,work,apply){abierto=true;editando=true;controls();el('editor').replaceChildren();el('editor').append(n('h2',title));const form=n('form');el('editor').append(form);const contenido=n('div');form.append(contenido);const act=n('div');act.className='admin-acciones';const aplicar=n('button',a.aplicar);aplicar.type='submit';act.append(aplicar,boton(a.volver,()=>{if(!abierto||!form.dataset.sucio||confirm(a.conflicto))lista();}));form.append(act);form.oninput=()=>{form.dataset.sucio='1';aviso(a.pendiente);};form.onsubmit=e=>{e.preventDefault();try{apply();modificado();lista();}catch(err){aviso(err.message);}};return {form,contenido};}
function editar(p,add=false){const work=structuredClone(p);const {form,contenido}=formBase(a.editar+' · '+p.nombre,work,()=>{const next=structuredClone(c);if(add)next.proyectos.push(work);else next.proyectos[next.proyectos.findIndex(x=>x.id===work.id)]=work;validarProyectos(next);c=next;});campos(work,contenido,'',form);}
function configurar(){const work=structuredClone({presentacion:c.presentacion,contacto:c.contacto,categorias:c.categorias});const {form,contenido}=formBase(a.configuracion,work,()=>{const next={...c,...work};validarProyectos(next);c=next;});campos(work,contenido,'',form);}
function campos(obj,dest,path,form){const grid=n('div');grid.className='admin-proyecto-campos';dest.append(grid);for(const [key,value] of Object.entries(obj)){const ruta=path?path+'.'+key:key;const label=t.campos[key]||key;
 if(Array.isArray(value)){const fs=n('fieldset');fs.className='campo-largo';fs.append(n('legend',label));const list=n('div');fs.append(list);grid.append(fs);function render(){list.replaceChildren();value.forEach((x,i)=>{const box=n('div');box.className='admin-array-item';list.append(box);campos(x,box,ruta+'.'+i,form);box.append(boton(a.quitar,()=>{value.splice(i,1);form.dataset.sucio='1';render();}));});}render();fs.append(boton(a.anadir,()=>{const templates={categorias:()=>({id:uid('categoria'),nombre:a.nuevaCategoria}),etapas:()=>({titulo:a.nuevaEtapa,texto:a.nuevoTexto,imagen:'',visible:true}),detalles:()=>({titulo:a.nuevoDetalle,texto:a.nuevoTexto}),galeria:()=>({imagen:'/assets/imagenes/proyectos/proceso-diseno.webp',pie:a.nuevoPie,alternativo:a.nuevoPie}),videos:()=>({titulo:a.nuevoVideo,url:''})};value.push(templates[key]());form.dataset.sucio='1';render();}));continue;}
 if(value&&typeof value==='object'){const fs=n('fieldset');fs.className='campo-largo';fs.append(n('legend',label));grid.append(fs);campos(value,fs,ruta,form);continue;}
 const lab=n('label');lab.append(n('span',label));const long=['resumen','descripcion','texto','materiales','nota','mensaje','alcance','enfoque'].includes(key);if(long)lab.className='campo-largo';let input;
 if(['categoria','estado','formato'].includes(key)){input=n('select');const values=key==='categoria'?c.categorias.map(x=>[x.id,x.nombre]):key==='estado'?Object.entries(t.estados):[['normal',a.formatoNormal],['grande',a.formatoGrande],['ancho',a.formatoAncho]];for(const [id,name]of values)input.append(new Option(name,id));input.value=value;}
 else{input=n(long?'textarea':'input');if(!long)input.type=typeof value==='boolean'?'checkbox':typeof value==='number'?'number':key==='url'?'url':'text';if(typeof value==='boolean')input.checked=value;else input.value=value;}
 input.name=ruta;input.required=typeof value!=='boolean'&&!['nota','producto','imagen'].includes(key);if(key==='imagen'&&path==='')input.required=true;if(input.type==='number'){input.min='0';input.max='100000';input.step='1';}if(['id','ruta'].includes(key))input.readOnly=true;lab.append(input);grid.append(lab);
 input.addEventListener('input',()=>{obj[key]=typeof value==='boolean'?input.checked:typeof value==='number'?Number(input.value):input.value;});input.addEventListener('change',()=>{obj[key]=typeof value==='boolean'?input.checked:typeof value==='number'?Number(input.value):input.value;});
 if(key==='imagen'){const preview=n('img');preview.className='admin-proyecto-foto';preview.alt=a.vista;preview.src=value;preview.hidden=!value;lab.append(preview);input.addEventListener('change',()=>{preview.src=input.value;preview.hidden=!input.value;});const up=n('input');up.type='file';up.accept='image/png,image/jpeg,image/webp';up.setAttribute('aria-label',a.subir);lab.append(up);up.onchange=async()=>{if(!up.files[0])return;busy=true;form.inert=true;controls();try{const ruta=await subirImagen(up.files[0]);input.value=ruta;obj[key]=ruta;preview.src=ruta;preview.hidden=false;form.dataset.sucio='1';aviso(a.imagenLista);}catch(e){aviso(e.message);}finally{busy=false;form.inert=false;up.value='';controls();}};}
 }}
async function guardar(){if(busy||editando)return;busy=true;document.querySelector('main').inert=true;controls();aviso(a.guardando);try{validarProyectos(c);const r=await api('documentos/proyectos',{method:'PUT',body:JSON.stringify({contenido:c,revision})});c=r.contenido;revision=r.revision;dirty=false;aviso(r.sinCambios?a.sinCambios:a.guardado);}catch(e){aviso(e.message);}finally{busy=false;document.querySelector('main').inert=false;controls();}}
async function respaldos(){try{const rows=await api('documentos/proyectos/respaldos');const d=n('dialog');d.className='admin-respaldo';d.append(n('h2',a.copia),boton(t.cerrar,()=>d.close()));if(!rows.length)d.append(n('p',a.sinRespaldos));const detail=n('div');for(const r of rows){d.append(boton(new Intl.DateTimeFormat('es-CO',{dateStyle:'medium',timeStyle:'short',timeZone:'America/Bogota'}).format(new Date(r.fecha)),async()=>{try{const data=await api('documentos/proyectos/respaldos/'+r.id);validarProyectos(data.catalogo);detail.replaceChildren();detail.append(n('p',data.catalogo.proyectos.length+' '+t.contador));const pre=n('pre',data.catalogo.proyectos.map(p=>p.nombre).join('\n'));detail.append(pre,boton(a.usar,()=>{if(confirm(a.confirmarRestaurar)){c=structuredClone(data.catalogo);dirty=true;lista();aviso(a.restaurado);d.close();}}));}catch(e){aviso(e.message);}}));}d.append(detail);d.addEventListener('close',()=>d.remove(),{once:true});document.body.append(d);d.showModal();}catch(e){aviso(e.message);}}
try{const [text,data]=await Promise.all([leerJSON('/src/idiomas/es/proyectos.json'),api('documentos/proyectos')]);t=text;a=t.admin;c=validarProyectos(data.contenido);revision=data.revision;el('titulo').textContent=a.titulo;el('guardar').textContent=a.guardar;el('respaldos').textContent=a.respaldos;el('guardar').onclick=guardar;el('respaldos').onclick=respaldos;lista();}catch(e){aviso(e.message);}
window.addEventListener('beforeunload',e=>{if(dirty||busy||(abierto&&el('editor').querySelector('form')?.dataset.sucio)){e.preventDefault();e.returnValue='';}});
