import { leerJSON } from '/src/servicios/archivos.js';
import { validarProyectos } from '/src/servicios/validadores/proyectos.js';
import { cargarContenidoInicio } from '/src/servicios/configuracion-sitio.js';
import { montarNavegacion } from '/src/componentes/navegacion/navegacion.js';
import { montarPie } from '/src/componentes/pie-pagina/pie-pagina.js';
import { icono } from '/src/componentes/tienda/iconos.js';
const el = id => document.getElementById(id);
const n = (tag, cls, text) => { const e = document.createElement(tag); if(cls)e.className=cls; if(text!==undefined)e.textContent=text; return e; };
const image = (src, alt, eager=false) => { const i=n('img'); i.src=src;i.alt=alt;i.width=1536;i.height=1024;i.loading=eager?'eager':'lazy';if(eager)i.fetchPriority='high';i.addEventListener('error',()=>{i.classList.add('imagen-falta');}); return i; };
const link = (text, url, cls) => { const a=n('a',cls,text);a.href=url;return a; };
const iconoProyecto = tipo => {const i=n('img','proyecto-icono');i.src='/assets/iconos/proyectos/'+tipo+'.svg';i.alt='';i.setAttribute('aria-hidden','true');i.width=24;i.height=24;return i;};
let t;
try {
 const [raw,textos,comun,inicio] = await Promise.all([leerJSON('/datos/contenido-inicial/proyectos.es.json'),leerJSON('/src/idiomas/es/proyectos.json'),leerJSON('/src/idiomas/es/comun.json'),cargarContenidoInicio()]);
 const piloto=await leerJSON('/datos/contenido-inicial/software-proyecto.es.json'); if(!raw.proyectos.some(p=>p.id===piloto.id)) raw.proyectos.push(piloto);
 const c=validarProyectos(raw);t=textos;montarNavegacion(el('cabecera'),comun.navegacion);montarPie(el('pie'),comun.pie);el('saltar').textContent=t.saltar;
 for(const a of el('cabecera').querySelectorAll('nav a'))if(new URL(a.href).pathname==='/paginas/proyectos/index.html')a.setAttribute('aria-current','page');
 const visible = c.proyectos.filter(p=>p.visible).sort((a,b)=>Number(b.destacado)-Number(a.destacado)||a.orden-b.orden);
 const view=el('vista');
 const whatsapp = (title,message) => { const a=link(title,'https://wa.me/'+inicio.contacto.whatsapp+'?text='+encodeURIComponent(message),'proyectos-whatsapp');a.prepend(icono('whatsapp'));a.target='_blank';a.rel='noopener noreferrer';return a; };
 function contacto(titulo,descripcion,boton,mensaje,conIcono=false) {const s=n('section','proyectos-contacto');const text=n('div');text.append(n('h2',null,titulo),n('p',null,descripcion));if(conIcono){text.className='proyecto-contacto-texto';text.prepend(iconoProyecto('conversacion'));}s.append(text,whatsapp(boton,mensaje));return s;}
 if(document.body.dataset.vista==='galeria') {
   document.title=c.presentacion.titulo+' — Roser Tecnologías';document.querySelector('meta[name=description]').content=c.presentacion.descripcion;
   const h=n('header','proyectos-intro');h.append(n('p','proyectos-etiqueta',c.presentacion.etiqueta),n('h1',null,c.presentacion.titulo),n('p','proyectos-lema',c.presentacion.descripcion));view.append(h);
   const top=n('div','proyectos-galeria-cabecera');top.append(n('h2',null,c.presentacion.galeriaTitulo));const cuenta=n('span','proyectos-cuenta');cuenta.setAttribute('role','status');top.append(cuenta);view.append(top);
   const filtros=n('nav','proyectos-filtros');filtros.setAttribute('aria-label',c.presentacion.galeriaTitulo);view.append(filtros);
   if(c.presentacion.mostrarNota&&c.presentacion.nota)view.append(n('p','proyectos-nota',c.presentacion.nota));
   const grid=n('div','proyectos-mosaico');grid.id='proyectos-mosaico';view.append(grid);
   let seleccionado=new URLSearchParams(location.search).get('categoria')||'';
   if(!c.categorias.some(x=>x.id===seleccionado))seleccionado='';
   function render(){const ps=visible.filter(p=>!seleccionado||p.categoria===seleccionado);cuenta.textContent=ps.length+' '+t.contador;grid.replaceChildren();for(const p of ps){const a=link('',p.ruta,'proyecto-tile proyecto-'+p.formato);a.setAttribute('aria-label',p.nombre+' — '+t.estados[p.estado]);a.append(image(p.imagen,p.alternativo,grid.children.length<3));const text=n('div','proyecto-tile-texto');text.append(n('h3',null,p.nombre),n('span','proyecto-estado',t.estados[p.estado]));const flecha=n('span','proyecto-flecha','→');flecha.setAttribute('aria-hidden','true');text.append(flecha);a.append(text);grid.append(a);}if(!ps.length)grid.append(n('p',null,t.vacio));for(const b of filtros.children)b.setAttribute('aria-pressed',String(b.dataset.categoria===seleccionado));}
   for(const cat of [{id:'',nombre:t.todos},...c.categorias.filter(x=>visible.some(p=>p.categoria===x.id))]){const b=n('button',null,cat.nombre);b.type='button';b.dataset.categoria=cat.id;b.setAttribute('aria-controls','proyectos-mosaico');b.onclick=()=>{seleccionado=cat.id;const u=new URL(location);if(seleccionado)u.searchParams.set('categoria',seleccionado);else u.searchParams.delete('categoria');history.replaceState(null,'',u);render();};filtros.append(b);}render();
   view.append(contacto(c.contacto.titulo,c.contacto.descripcion,c.contacto.boton,c.contacto.mensaje));
 } else {
   const id=document.body.dataset.proyecto||new URLSearchParams(location.search).get('id');const p=visible.find(p=>p.id===id);
   if(!p){view.append(n('h1',null,t.noProyecto),link(t.volver,'/paginas/proyectos/index.html'));throw Error(t.noProyecto);}
   document.title=p.nombre+' — Roser Tecnologías';document.querySelector('meta[name=description]').content=p.resumen;
   const head=n('header','proyecto-presentacion');const cats=c.categorias.find(x=>x.id===p.categoria);const titulo=n('div','proyecto-titulo');titulo.append(n('h1',null,p.nombre));const clasificacion=n('div','proyecto-clasificacion');clasificacion.append(n('p','proyectos-etiqueta',cats.nombre),n('span','proyecto-estado',t.estados[p.estado]));titulo.append(clasificacion,n('p','proyectos-lema',p.resumen));head.append(titulo);if(p.nota)head.append(n('p','proyectos-nota',p.nota));view.append(head);
   const figure=n('figure','proyecto-principal');const main=n('button','proyecto-ampliar');main.type='button';main.setAttribute('aria-label',t.ampliar+': '+p.nombre);main.append(image(p.imagen,p.alternativo,true));figure.append(main);view.append(figure);
   const meta=n('dl','proyecto-meta');for(const [k,val] of [['alcance',p.alcance],['enfoque',p.enfoque],['estado',t.estados[p.estado]]]){const box=n('div');const dt=n('dt',null,t[k]);dt.prepend(iconoProyecto(k));box.append(dt,n('dd',null,val));meta.append(box);}view.append(meta);
   const slides=[{imagen:p.imagen,alternativo:p.alternativo,pie:p.nombre},...p.galeria];main.onclick=()=>abrirVisor(0);
   const etapas=p.etapas.filter(e=>e.visible);if(p.mostrarEtapas&&etapas.length){const sec=n('section','proyecto-seccion');sec.append(n('h2',null,t.proceso));const etapasGrid=n('div','proyecto-etapas');for(const [i,e] of etapas.entries()){const art=n('article');const title=n('h3');title.append(n('span','proyecto-numero',String(i+1).padStart(2,'0')),n('span',null,e.titulo));art.append(title);if(e.imagen){const b=n('button','proyecto-ampliar');b.type='button';b.setAttribute('aria-label',t.ampliar+': '+e.titulo);b.append(image(e.imagen,e.titulo+' — '+p.nombre));const index=slides.push({imagen:e.imagen,alternativo:e.titulo,pie:e.titulo})-1;b.onclick=()=>abrirVisor(index);art.append(b);}art.append(n('p',null,e.texto));etapasGrid.append(art);}sec.append(etapasGrid);view.append(sec);}
   if(p.mostrarDetalles){const sec=n('section','proyecto-seccion');sec.append(n('h2',null,t.detalles));const det=n('div','proyecto-detalles');for(const [i,d] of p.detalles.entries()){const art=n('article');const h=n('h3',null,d.titulo);h.prepend(iconoProyecto(i%2?'materiales':'diseno'));const texto=n('div');texto.append(h,n('p',null,d.texto));const ico=h.querySelector('.proyecto-icono');h.removeChild(ico);art.append(ico,texto);det.append(art);}const mat=n('h3','proyecto-materiales',t.materiales);mat.prepend(iconoProyecto('materiales'));sec.append(det);if(!p.detalles.some(d=>d.texto.trim()===p.materiales.trim())){const materiales=n('div','proyecto-materiales-bloque');materiales.append(mat,n('p',null,p.materiales));sec.append(materiales);}view.append(sec);}
   if(p.mostrarGaleria&&p.galeria.length){const sec=n('section','proyecto-seccion');sec.append(n('h2',null,t.galeria));const g=n('div','proyecto-galeria');if(p.galeria.length===2)g.classList.add('proyecto-galeria-dos');for(const [i,img] of p.galeria.entries()){const f=n('figure');const b=n('button','proyecto-ampliar');b.type='button';b.setAttribute('aria-label',t.ampliar+': '+img.alternativo);b.append(image(img.imagen,img.alternativo));const ampliar=n('span','proyecto-indicador-ampliar');ampliar.setAttribute('aria-hidden','true');ampliar.append(iconoProyecto('ampliar'));b.append(ampliar);b.onclick=()=>abrirVisor(i+1);f.append(b,n('figcaption',null,img.pie));g.append(f);}sec.append(g);view.append(sec);}
   if(p.videos.length){const s=n('section','proyecto-seccion');s.append(n('h2',null,t.videos));for(const v of p.videos){const a=link(v.titulo+' ↗',v.url,'proyecto-video');a.target='_blank';a.rel='noopener noreferrer';s.append(a);}view.append(s);}
   if(p.producto)view.append(link(t.producto,'/paginas/productos/ficha/index.html?id='+encodeURIComponent(p.producto),'proyecto-volver'));
   const cierre=contacto(t.similar,t.similarTexto,t.consulta,p.mensaje,true);cierre.classList.add('proyecto-contacto-final');const explorar=n('div','proyecto-explorar');explorar.append(link(t.explorar,'/paginas/proyectos/index.html','proyecto-volver'));cierre.append(explorar);view.append(cierre);
   let index=0;const dialog=el('visor');function show(){const x=slides[index];el('visor-imagen').src=x.imagen;el('visor-imagen').alt=x.alternativo;el('visor-pie').textContent=x.pie;el('visor-cuenta').textContent=(index+1)+' / '+slides.length;}
   function abrirVisor(i){index=i;show();if(!dialog.open)dialog.showModal();}const move=d=>{index=(index+d+slides.length)%slides.length;show();};
   el('visor-cerrar').textContent=t.cerrar;el('visor-cerrar').onclick=()=>dialog.close();el('visor-anterior').textContent='←';el('visor-anterior').setAttribute('aria-label',t.anterior);el('visor-anterior').onclick=()=>move(-1);el('visor-siguiente').textContent='→';el('visor-siguiente').setAttribute('aria-label',t.siguiente);el('visor-siguiente').onclick=()=>move(1);dialog.addEventListener('keydown',e=>{if(e.key==='ArrowRight')move(1);if(e.key==='ArrowLeft')move(-1);});dialog.addEventListener('click',e=>{if(e.target===dialog){const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)dialog.close();}});
 }
} catch(e) {console.error(e);el('estado').textContent=e.message||t?.error;el('estado').hidden=false;}
